# Generated by Django 4.0.2 on 2022-02-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lesson_images')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_images')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfoliolar',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_images')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='cv')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumelar',
            },
        ),
        migrations.CreateModel(
            name='SofialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=300)),
                ('telegram', models.URLField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('linkedin', models.URLField()),
                ('youtube', models.URLField()),
            ],
            options={
                'verbose_name': 'SocialLink',
                'verbose_name_plural': 'SocialLinks',
            },
        ),
    ]
