# Generated by Django 4.0.2 on 2022-02-18 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_visitors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitors',
            old_name='count',
            new_name='soni',
        ),
    ]
